### ISSUE TITLE
darkside.c line 97-100 

### ISSUE THREAD

**Issue by NightyBoi** [Elektropioneer/MainBoard_Framework#3]
Empty else if?
delete or add ''sprinkle water'' or something like that?

**Comment by silardg** [comment]
Empty else if will be removed in next commit. 
We never used it, it was copied over from the last repo, but we may use it, but for now it will be deleted.

What do you mean by "sprinkle water"?

@PlaguedByWeirdness

**Comment by silardg** [comment]
@PlaguedByWeirdness 
The empty `else if` was removed and updated in the dev branch.
Still, what the hell does "sprinkle water" mean?

**Comment by NightyBoi** [comment]
I don't know, I thought we could get extra points if the robot sprinkles water around if it gets stuck, special effects here and there, y'know?
